version: '3.8'

services:
  ppt-maker:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_data:
